
name: Update Database and Plots
title: '[BOT] Update Plots and Database'
labels: 'bot'

body:
  - type: checkboxes
    attributes:
      label: Update Options
      description: Select the options you want to update.
      options:
        - label: Update Database
          id: update_database
          required: false
        - label: Update Plots
          id: update_plots
   
  - type: markdown
    attributes:
      value: |
        This issue will automatically create a pull request with the appropriate title based on the selected options.
