
name: Update Database and Plots
description: Creates a new issue
title: '[BOT] Update Plots and Database'
labels: 'bot'

body:

  - type: markdown
    attributes:
      value: |
        This issue will automatically create a pull request with the appropriate title based on the selected options.
