stadium_info_dict = {
    "Arizona Cardinals": {
        "name": "State Farm Stadium",
        "city": "Glendale",
        "state": "Arizona",
        "latitude": 33.5275,
        "longitude": -112.2625,
        "roof_type": "Retractable",
    },
    "Atlanta Falcons": {
        "name": "Mercedes-Benz Stadium",
        "city": "Atlanta",
        "state": "Georgia",
        "latitude": 33.755,
        "longitude": -84.4005,
        "roof_type": "Retractable",
    },
    "Baltimore Ravens": {
        "name": "M&T Bank Stadium",
        "city": "Baltimore",
        "state": "Maryland",
        "latitude": 39.2775,
        "longitude": -76.6225,
        "roof_type": "Open",
    },
    "Buffalo Bills": {
        "name": "Highmark Stadium",
        "city": "Orchard Park",
        "state": "New York",
        "latitude": 42.773,
        "longitude": -78.7865,
        "roof_type": "Open",
    },
    "Carolina Panthers": {
        "name": "Bank of America Stadium",
        "city": "Charlotte",
        "state": "North Carolina",
        "latitude": 35.225,
        "longitude": -80.8525,
        "roof_type": "Open",
    },
    "Chicago Bears": {
        "name": "Soldier Field",
        "city": "Chicago",
        "state": "Illinois",
        "latitude": 41.8625,
        "longitude": -87.6165,
        "roof_type": "Open",
    },
    "Cincinnati Bengals": {
        "name": "Paycor Stadium",
        "city": "Cincinnati",
        "state": "Ohio",
        "latitude": 39.095,
        "longitude": -84.5165,
        "roof_type": "Open",
    },
    "Cleveland Browns": {
        "name": "FirstEnergy Stadium",
        "city": "Cleveland",
        "state": "Ohio",
        "latitude": 41.5065,
        "longitude": -81.6995,
        "roof_type": "Open",
    },
    "Dallas Cowboys": {
        "name": "AT&T Stadium",
        "city": "Arlington",
        "state": "Texas",
        "latitude": 32.7475,
        "longitude": -97.0925,
        "roof_type": "Retractable",
    },
    "Denver Broncos": {
        "name": "Empower Field at Mile High",
        "city": "Denver",
        "state": "Colorado",
        "latitude": 39.7435,
        "longitude": -105.0205,
        "roof_type": "Open",
    },
    "Detroit Lions": {
        "name": "Ford Field",
        "city": "Detroit",
        "state": "Michigan",
        "latitude": 42.3415,
        "longitude": -83.0455,
        "roof_type": "Closed",
    },
    "Green Bay Packers": {
        "name": "Lambeau Field",
        "city": "Green Bay",
        "state": "Wisconsin",
        "latitude": 44.5015,
        "longitude": -88.0625,
        "roof_type": "Open",
    },
    "Houston Texans": {
        "name": "NRG Stadium",
        "city": "Houston",
        "state": "Texas",
        "latitude": 29.6845,
        "longitude": -95.4105,
        "roof_type": "Retractable",
    },
    "Indianapolis Colts": {
        "name": "Lucas Oil Stadium",
        "city": "Indianapolis",
        "state": "Indiana",
        "latitude": 39.7605,
        "longitude": -86.1635,
        "roof_type": "Retractable",
    },
    "Jacksonville Jaguars": {
        "name": "TIAA Bank Field",
        "city": "Jacksonville",
        "state": "Florida",
        "latitude": 30.3235,
        "longitude": -81.6375,
        "roof_type": "Open",
    },
    "Kansas City Chiefs": {
        "name": "GEHA Field at Arrowhead Stadium",
        "city": "Kansas City",
        "state": "Missouri",
        "latitude": 39.0485,
        "longitude": -94.4835,
        "roof_type": "Open",
    },
    "Las Vegas Raiders": {
        "name": "Allegiant Stadium",
        "city": "Las Vegas",
        "state": "Nevada",
        "latitude": 36.0902,
        "longitude": -115.1854,
        "roof_type": "Retractable",
    },
    "Los Angeles Chargers": {
        "name": "SoFi Stadium",
        "city": "Inglewood",
        "state": "California",
        "latitude": 33.9533,
        "longitude": -118.3392,
        "roof_type": "Retractable",
    },
    "Los Angeles Rams": {
        "name": "SoFi Stadium",
        "city": "Inglewood",
        "state": "California",
        "latitude": 33.9533,
        "longitude": -118.3392,
        "roof_type": "Retractable",
    },
    "Miami Dolphins": {
        "name": "Hard Rock Stadium",
        "city": "Miami Gardens",
        "state": "Florida",
        "latitude": 25.9585,
        "longitude": -80.2385,
        "roof_type": "Retractable",
    },
    "Minnesota Vikings": {
        "name": "U.S. Bank Stadium",
        "city": "Minneapolis",
        "state": "Minnesota",
        "latitude": 44.9745,
        "longitude": -93.2585,
        "roof_type": "Closed",
    },
    "New England Patriots": {
        "name": "Gillette Stadium",
        "city": "Foxborough",
        "state": "Massachusetts",
        "latitude": 42.0905,
        "longitude": -71.2645,
        "roof_type": "Open",
    },
    "New Orleans Saints": {
        "name": "Caesars Superdome",
        "city": "New Orleans",
        "state": "Louisiana",
        "latitude": 29.9495,
        "longitude": -90.0815,
        "roof_type": "Closed",
    },
    "New York Giants": {
        "name": "MetLife Stadium",
        "city": "East Rutherford",
        "state": "New Jersey",
        "latitude": 40.8135,
        "longitude": -74.0745,
        "roof_type": "Open",
    },
    "New York Jets": {
        "name": "MetLife Stadium",
        "city": "East Rutherford",
        "state": "New Jersey",
        "latitude": 40.8135,
        "longitude": -74.0745,
        "roof_type": "Open",
    },
    "Philadelphia Eagles": {
        "name": "Lincoln Financial Field",
        "city": "Philadelphia",
        "state": "Pennsylvania",
        "latitude": 39.9015,
        "longitude": -75.1675,
        "roof_type": "Open",
    },
    "Pittsburgh Steelers": {
        "name": "Acrisure Stadium",
        "city": "Pittsburgh",
        "state": "Pennsylvania",
        "latitude": 40.4465,
        "longitude": -80.0155,
        "roof_type": "Open",
    },
    "San Francisco 49ers": {
        "name": "Levi's Stadium",
        "city": "Santa Clara",
        "state": "California",
        "latitude": 37.4035,
        "longitude": -121.9695,
        "roof_type": "Open",
    },
    "Seattle Seahawks": {
        "name": "Lumen Field",
        "city": "Seattle",
        "state": "Washington",
        "latitude": 47.5955,
        "longitude": -122.3315,
        "roof_type": "Open",
    },
    "Tampa Bay Buccaneers": {
        "name": "Raymond James Stadium",
        "city": "Tampa",
        "state": "Florida",
        "latitude": 27.9755,
        "longitude": -82.5035,
        "roof_type": "Open",
    },
    "Tennessee Titans": {
        "name": "Nissan Stadium",
        "city": "Nashville",
        "state": "Tennessee",
        "latitude": 36.1665,
        "longitude": -86.7715,
        "roof_type": "Open",
    },
    "Washington Commanders": {
        "name": "FedExField",
        "city": "Landover",
        "state": "Maryland",
        "latitude": 38.9075,
        "longitude": -76.8645,
        "roof_type": "Open",
    },
}