name: Create Pull Request

on:
  issues:
    types: [opened]

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Determine Title
      id: determine_title
      run: |
        ISSUE_BODY="${{ github.event.issue.body }}"
        if [[ "$ISSUE_BODY" == *"- [x] Update Database"* && "$ISSUE_BODY" == *"- [x] Update Plots"* ]]; then
          echo "::set-output name=title::[BOT] Update Database and Plots"
        elif [[ "$ISSUE_BODY" == *"- [x] Update Database"* ]]; then
          echo "::set-output name=title::[BOT] Update Database"
        elif [[ "$ISSUE_BODY" == *"- [x] Update Plots"* ]]; then
          echo "::set-output name=title::[BOT] Update Plots"
        else
          echo "No valid options selected. Exiting."
          exit 1

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: '[BOT] Automated update of database and plots'
        branch: 'update-database-and-plots'
        title: ${{ steps.determine_title.outputs.title }}
        body: 'This pull request was automatically created to update the database and plots.'