name: Create Pull Request

on:
  issues:
    types: [opened]

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Determine Title
      id: determine_title
      run: |
        ISSUE_TITLE="${{ github.event.issue.title }}"
        if [[ "$ISSUE_TITLE" == *"[BOT] Update Database and Plots"* ]]; then
          echo "::set-output name=title::[BOT] Update Database and Plots"
        elif [[ "$ISSUE_TITLE" == *"[BOT] Update Database"* ]]; then
          echo "::set-output name=title::[BOT] Update Database"
        elif [[ "$ISSUE_TITLE" == *"[BOT] Update Plots"* ]]; then
          echo "::set-output name=title::[BOT] Update Plots"
        else
          echo "No valid options selected. Exiting."
          exit 1
        fi

    - name: Create Branch
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        BRANCH_NAME="issue-${ISSUE_NUMBER}"
        git checkout -b $BRANCH_NAME
        echo "::set-output name=branch_name::$BRANCH_NAME"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: '[BOT] Automated update of database and plots'
        branch: ${{ steps.create_branch.outputs.branch_name }}
        title: ${{ steps.determine_title.outputs.title }}
        body: 'This pull request was automatically created to update the database and plots.'