name: Create Pull Request

on:
  issues:
    types: [opened]

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Determine Title
      id: determine_title
      run: |
        ISSUE_TITLE="${{ github.event.issue.title }}"
        if [[ "$ISSUE_TITLE" == *"[BOT] Update Database and Plots"* ]]; then
          echo "::set-output name=title::[BOT] Update Database and Plots"
        elif [[ "$ISSUE_TITLE" == *"[BOT] Update Database"* ]]; then
          echo "::set-output name=title::[BOT] Update Database"
        elif [[ "$ISSUE_TITLE" == *"[BOT] Update Plots"* ]]; then
          echo "::set-output name=title::[BOT] Update Plots"
        else
          echo "No valid options selected. Exiting."
          exit 1
        fi

    - name: Create Branch
      id: create_branch
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        BRANCH_NAME="issue-${ISSUE_NUMBER}"
        git checkout -b $BRANCH_NAME
        echo "Temporary file content" > .temp
        git config user.email $EMAIL
        git config user.name $USERNAME
        git commit --allow-empty -m "Empty commit"
        git push origin main
        echo "::set-output name=branch_name::$BRANCH_NAME"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EMAIL: ${{ secrets.K_EMAIL }}
        USERNAME: ${{ secrets.K_USERNAME }}
        

    - name: Create Pull Request
      run: |
        gh pr create -B main -H $BRANCH_NAME --title "$TITLE" --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ steps.create_branch.outputs.branch_name }}
          TITLE: ${{ steps.determine_title.outputs.title }}
