name: Create Pull Request

on:
  issues:
    types: [opened]

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Determine Title
      id: determine_title
      run: |
        ISSUE_TITLE="${{ github.event.issue.title }}"
        if [[ "$ISSUE_TITLE" == *"[BOT] Update Database and Plots"* ]]; then
          echo "::set-output name=title::[BOT] Update Database and Plots"
        elif [[ "$ISSUE_TITLE" == *"[BOT] Update Database"* ]]; then
          echo "::set-output name=title::[BOT] Update Database"
        elif [[ "$ISSUE_TITLE" == *"[BOT] Update Plots"* ]]; then
          echo "::set-output name=title::[BOT] Update Plots"
        elif [[ "$ISSUE_TITLE" == *"[BOT] Update Weather"* ]]; then
          echo "::set-output name=title::[BOT] Update Weather"
        else
          echo "No valid options selected. Exiting."
          exit 1
        fi

    - name: Create Branch
      id: create_branch
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        BRANCH_NAME="issue-${ISSUE_NUMBER}"
        git checkout -b $BRANCH_NAME
        git push --set-upstream origin $BRANCH_NAME
        echo "::set-output name=branch_name::$BRANCH_NAME"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Temp File
      run: echo "Temporary file content" > .temp
      
    - name: Stage changes
      run: git add -A

    - name: Check for changes
      run: |
        git status
        git diff

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: '.'
        default_author: github_actions
        message: '[BOT] Created Temp File'
        push: origin ${{ github.head_ref }}
        

    - name: Create Pull Request
      run: |
        gh pr create -B main -H $BRANCH_NAME --title "$TITLE" --body "Created by Github action. Closes #${ISSUE_NUMBER}"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ steps.create_branch.outputs.branch_name }}
          TITLE: ${{ steps.determine_title.outputs.title }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}

    - name: Dispatch Update Database Workflow
      if: steps.determine_title.outputs.title == '[BOT] Update Database'
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/killenden/NFL_stats/dispatches \
           -f "event_type=update-database" -F "client_payload[ref]=${{ steps.create_branch.outputs.branch_name }}" -F "client_payload[repo_name]=${{ github.event.repository.name }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Dispatch Update Plots Workflow
      if: steps.determine_title.outputs.title == '[BOT] Update Plots'
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/killenden/NFL_stats/dispatches \
           -f "event_type=update-plots" -F "client_payload[ref]=${{ steps.create_branch.outputs.branch_name }}" -F "client_payload[repo_name]=${{ github.event.repository.name }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Dispatch Update Database and Plots Workflow
      if: steps.determine_title.outputs.title == '[BOT] Update Database and Plots'
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/killenden/NFL_stats/dispatches \
           -f "event_type=update-database-and-plots" -F "client_payload[ref]=${{ steps.create_branch.outputs.branch_name }}" -F "client_payload[repo_name]=${{ github.event.repository.name }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Dispatch Weather Workflow
      if: steps.determine_title.outputs.title == '[BOT] Update Weather'
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/killenden/NFL_stats/dispatches \
           -f "event_type=update-weather" -F "client_payload[ref]=${{ steps.create_branch.outputs.branch_name }}" -F "client_payload[repo_name]=${{ github.event.repository.name }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
