name: Extract DB Number from Commit Message and Run Python Script

on:
  push:
    branches:
      - main

jobs:
  extract_db_number:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set Year
      id: set_year
      run: |
        echo "db_number=2024" >> $GITHUB_ENV
        echo "::set-output name=db_number::2024"
      
    - name: Run Python script with DB number
      run: |
        db_number=${{ steps.set_year.outputs.db_number }}
        echo "The environment variable DB_NUMBER is: $db_number"
        echo "$PWD"
        python GitHubActions.py $db_number
      env:
        db_number: ${{ steps.set_year.outputs.db_number }}
