name: Extract DB Number from Commit Message and Run Python Script

on:
  push:
    branches:
      - main

jobs:
  extract_db_number:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set Year
      id: set_year
      run: |
        echo "db_number=2024" >> $GITHUB_ENV
        echo "::set-output name=db_number::2024"
      
    - name: Run Python script with DB number
      run: |
        echo "The environment variable DB_NUMBER is: $DB_NUMBER"
        DB_NUMBER=${{ steps.set_year.outputs.db_number }}
        
        # Ensure we don't run if DB number is undefined
        if [ "$DB_NUMBER" != "undefined" ]; then
          echo "Running Python script with DB number: $DB_NUMBER"
          cd ../../..
          python GitHubActions.py $DB_NUMBER
        else
          echo "No valid DB number found, skipping Python script."
      env:
        DB_NUMBER: ${{ steps.extract_db_number.outputs.db_number }}
