name: Extract DB Number from Commit Message and Run Python Script

on:
  push:
    branches:
      - main

jobs:
  extract_db_number:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set Year
      run: |
        steps.extract_db_number.outputs.db_number = 2024
      
    - name: Run Python script with DB number
      run: |
        DB_NUMBER=${{ steps.extract_db_number.outputs.db_number }}
        
        # Ensure we don't run if DB number is undefined
        if [ "$DB_NUMBER" != "undefined" ]; then
          echo "Running Python script with DB number: $DB_NUMBER"
          cd ../../..
          python GitHubActions.py $DB_NUMBER
        else
          echo "No valid DB number found, skipping Python script."
      env:
        DB_NUMBER: ${{ steps.extract_db_number.outputs.db_number }}
