name: Generate plots

on:
  push:
  schedule:
    - cron: '0 12 * * *'

jobs:
      
  generate_rb_plots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.18'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.26.4 beautifulsoup4 requests pandas==1.5.3 matplotlib==3.8.0

      - name: Delete old plots if they exist
        run: |
          find 2023/plots/ -name '*.png' -exec rm {} +

      - name: Run NFL_stats.py
        run: python NFL_stats.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "tonyillenden@gmail.com"
          git config --local user.name "anthony-illenden"
          git stash push -u
          git pull --rebase origin main
          # Pop the stash
          git stash pop
          git add 2023/plots/*.png
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update Plots"
            git push origin main
          fi
      
