name: Generate RB plot

on:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  generate_rb_plots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.18'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.26.4 beautifulsoup4 requests pandas==1.5.3 matplotlib==3.8.0

      - name: Delete old plots if they exist
        run: |
          if ls 2024/plots/*.png 1> /dev/null 2>&1; then rm 2024/plots/*.png; fi
      
      - name: Run NFL_stats.py
        run: python NFL_stats.py
      
      - name: Commit and push RB plot
        run: |
          git config --local user.email "tonyillenden@gmail.com"
          git config --local user.name "anthony-illenden"
          git stash push -u
          git pull --rebase origin main
          git stash pop
          git add 2024/plots/
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update RB Plot"
            git push origin main
          fi
