name: Run Python Stat File
on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 9 * * 2'
  pull_request:
    branches:
      - '**'  # Run on all branches for pull requests

jobs:
  run_stats_py_file:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib scikit-learn pysqlite3
      
    - name: Set Values
      id: set_values
      run: |
        echo "db_number=2024" >> $GITHUB_ENV
        echo "week_number=18" >> $GITHUB_ENV
        echo "::set-output name=db_number::2024"
        echo "::set-output name=week_number::18"
        
    - name: Ensure plots directory exists
      run: |
        db_number=${{ steps.set_values.outputs.db_number }}
        mkdir -p $db_number/plots

    - name: Delete old plots if they exist
      run: |
        db_number=${{ steps.set_values.outputs.db_number }}
        if [ -d "$db_number/plots" ]; then
          rm -r $db_number/plots/*
        fi

    - name: Run Python Script
      run: |
        python GitHubActions.py ${{ env.db_number }} ${{ env.week_number }}

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: './${{ steps.set_values.outputs.db_number }}/plots'
        default_author: github_actions
        message: '[BOT] Update graphs'
        push: origin ${{ github.head_ref }}
