name: Run Python Stat File
on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - '**'  # Run on all branches for pull requests

jobs:
  run_stats_py_file:
    if: contains(github.event.pull_request.title, 'Update Plots')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib scikit-learn pysqlite3 beautifulsoup4 requests
      
    - name: Set Values
      id: set_values
      run: |
        echo "db_number=2024" >> $GITHUB_ENV
        echo "week_number=18" >> $GITHUB_ENV
        echo "::set-output name=db_number::2024"
        echo "::set-output name=week_number::18"
        
    - name: Ensure plots directory exists
      run: |
        mkdir -p ${{ steps.set_values.outputs.db_number }}/plots

    - name: Delete old plots if they exist
      run: |
        db_number=${{ steps.set_values.outputs.db_number }}
        if [ -d "$db_number/plots" ]; then
          rm -r $db_number/plots/*
        fi

    - name: Run Python Script
      run: |
        python GitHubActions.py ${{ steps.set_values.outputs.db_number }} ${{ steps.set_values.outputs.week_number }}

    - name: Check for changes
      run: |
        git status
        git diff

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: |
          ./${{ steps.set_values.outputs.db_number }}/plots
          ./database/${{ steps.set_values.outputs.db_number }}.db
        default_author: github_actions
        message: '[BOT] Update graphs and database for DB number ${{ steps.set_values.outputs.db_number }}'
        push: origin ${{ github.head_ref }}
