name: Run Python Stat File
on:
  push:
    branches:
      - main

jobs:
  run_stats_py_file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib scikit-learn pysqlite3
      
    - name: Set Values
      id: set_values
      run: |
        echo "db_number=2024" >> $GITHUB_ENV
        echo "::set-output name=week_number::2024"
        echo "week_number=1" >> $GITHUB_ENV
        echo "::set-output name=week_number::1"
      
    - name: Run Python script with DB number
      run: |
        db_number=${{ steps.set_values.outputs.db_number }}
        week_number=${{ steps.set_values.outputs.week_number }}
        echo "The environment variable db_number is: $db_number"
        echo "The environment variable week_number is: $week_number"
        echo "$PWD"
        python GitHubActions.py $db_number $week_number
      env:
        db_number: ${{ steps.set_values.outputs.db_number }}
        week_number: ${{ steps.set_values.outputs.week_number }}
