name: Run Python Stat File
on:
  push:

jobs:
  run_stats_py_file:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib scikit-learn pysqlite3
      
    - name: Set Values
      id: set_values
      run: |
        echo "db_number=2024" >> $GITHUB_ENV
        echo "week_number=1" >> $GITHUB_ENV
        echo "::set-output name=db_number::2024"
        echo "::set-output name=week_number::1"
        
    - name: Delete old plots if they exist
      run: |
        db_number=${{ steps.set_values.outputs.db_number }}
        if [ -d "$db_number/plots" ]; then
          find "$db_number/plots/" -name '*.png' -exec rm -f {} +
          echo "Deleted old plots in $db_number/plots/"
        else
          echo "Directory $db_number/plots does not exist"
        fi

    - name: Run Python script with DB number
      run: |
        db_number=${{ steps.set_values.outputs.db_number }}
        week_number=${{ steps.set_values.outputs.week_number }}
        echo "The output db_number is: $db_number"
        echo "The output week_number is: $week_number"
        echo "$PWD"
        python GitHubActions.py $db_number $week_number
      env:
        db_number: ${{ steps.set_values.outputs.db_number }}
        week_number: ${{ steps.set_values.outputs.week_number }}
        
    - name: Commit and push changes
      run: |
          git config --local user.email "tonyillenden@gmail.com"
          git config --local user.name "anthony-illenden"
          git stash push -u
          git pull --rebase origin main
          # Pop the stash
          git stash pop
          git add $db_number/plots/*.png
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update Plots"
            git push origin main
          fi
      env:
        db_number: ${{ steps.set_values.outputs.db_number }}
