name: Update Plots
on:
  repository_dispatch:
    types: [update-plots]

jobs:
  delete_plots:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.client_payload.ref }}
        repository: killenden/${{ github.event.client_payload.repo_name }}


    - name: Print checked out branch
      run: |
        echo "Checked out branch: $(git rev-parse --abbrev-ref HEAD)"
        

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib scikit-learn pysqlite3 beautifulsoup4 requests datetime
    
    - name: Run stats/YearAndWeek.py script
      id: run_yearandweek
      run: |
        python stats/YearAndWeek.py > temp_output.txt
        echo "year=$(grep '^year=' temp_output.txt | cut -d'=' -f2-)" >> $GITHUB_OUTPUT
        echo "weeks=$(grep '^weeks=' temp_output.txt | cut -d'=' -f2-)" >> $GITHUB_OUTPUT
      
    - name: Print year and weeks
      run: |
        echo "Year: ${{ steps.run_yearandweek.outputs.year }}"
        echo "Weeks: ${{ steps.run_yearandweek.outputs.weeks }}"

    - name: Delete old plots if they exist
      run: |
        db_number=${{ steps.run_yearandweek.outputs.year }}
        if [ -d "$stats/plots/db_number" ]; then
          rm -r $stats/plots/db_number/*.png
          echo "plots_deleted=true" >> $GITHUB_ENV
        else
          echo "plots_deleted=false" >> $GITHUB_ENV
        fi
    
    - name: Set output
      id: set_output
      run: |
        echo "::set-output name=plots_deleted::${{ env.plots_deleted }}"
  
    - name: Print output
      run: |
        echo "Plots Deleted: ${{ steps.set_output.outputs.plots_deleted }}"

    - name: Delete Temp File
      run: |
        if [ -f ".temp" ]; then
          rm -r .temp
        fi

    - name: Stage changes
      run: |
        git add -A

    - name: Check for changes
      run: |
        git status
        git diff

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: '.'
        default_author: github_actions
        message: '[BOT] Delete graphs and database for DB number ${{ steps.run_yearandweek.outputs.year }}'
        push: origin ${{ github.head_ref }}

  update_plots:
    needs: delete_plots
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.client_payload.ref }}
        repository: killenden/${{ github.event.client_payload.repo_name }}
    
    - name: Print checked out branch
      run: |
        echo "Checked out branch: $(git rev-parse --abbrev-ref HEAD)"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib scikit-learn pysqlite3 beautifulsoup4 requests datetime
    
    - name: Run stats/YearAndWeek.py script
      id: run_yearandweek
      run: |
        python stats/YearAndWeek.py > temp_output.txt
        echo "year=$(grep '^year=' temp_output.txt | cut -d'=' -f2-)" >> $GITHUB_OUTPUT
        echo "weeks=$(grep '^weeks=' temp_output.txt | cut -d'=' -f2-)" >> $GITHUB_OUTPUT
      
    - name: Print year and weeks
      run: |
        echo "Year: ${{ steps.run_yearandweek.outputs.year }}"
        echo "Weeks: ${{ steps.run_yearandweek.outputs.weeks }}"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib scikit-learn beautifulsoup4 requests datetime

    - name: Run stats/GitHubActions.py Script
      run: |
        python stats/GitHubActions.py ${{ steps.run_yearandweek.outputs.year }} ${{ steps.run_yearandweek.outputs.weeks }}

    - name: Stage changes
      run: |
        git add -A

    - name: Check for changes
      run: |
        git status
        git diff

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: |
          ./stats/plots/${{ steps.run_yearandweek.outputs.year }}/plots
        default_author: github_actions
        message: '[BOT] Update graphs for DB number ${{ steps.run_yearandweek.outputs.year }}'
        push: origin ${{ github.head_ref }}
    

