name: Update DB and Plots
on:
  repository_dispatch:
    types: [update_db_and_plots]

jobs:
  update_db_and_plots:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.client_payload.branch }}
        repository: ${{ github.repository }}

    - name: Set Values
      id: set_values
      run: |
        echo "db_number=${{ github.event.client_payload.db_number }}" >> $GITHUB_ENV
        echo "week_number=${{ github.event.client_payload.week_number }}" >> $GITHUB_ENV
        echo "::set-output name=db_number::${{ github.event.client_payload.db_number }}"
        echo "::set-output name=week_number::${{ github.event.client_payload.week_number }}"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib scikit-learn pysqlite3 beautifulsoup4 requests

    - name: Run FootballDB/main.py script
      run: python FootballDB/main.py

    - name: Run GitHubActions.py Script
      run: |
        python GitHubActions.py ${{ env.db_number }} ${{ env.week_number }}

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: |
          ./${{ steps.set_values.outputs.db_number }}/plots
          ./database/${{ steps.set_values.outputs.db_number }}.db
        default_author: github_actions
        message: '[BOT] Update graphs and database for DB number ${{ steps.set_values.outputs.db_number }}'
        push: origin ${{ github.event.client_payload.branch }}
    
