name: Update DB
on:
  repository_dispatch:
    types: [update-database]

jobs:
  delete_db:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.client_payload.ref }}
        repository: ${{ github.event.client_payload.repo_name }}

    - name: Print checked out branch
      run: |
        echo "Checked out branch: $(git rev-parse --abbrev-ref HEAD)"
        

    - name: Set Values
      id: set_values
      run: |
        echo "db_number=2024" >> $GITHUB_ENV
        echo "week_number=18" >> $GITHUB_ENV
        echo "::set-output name=db_number::2024"
        echo "::set-output name=week_number::18"

    - name: Delete old db if they exist
      run: |
        db_number=${{ steps.set_values.outputs.db_number }}
        if [ -f "database/$db_number.db" ]; then
          rm -r database/$db_number.db
          echo "db_deleted=true" >> $GITHUB_ENV
        else
          echo "db_deleted=false" >> $GITHUB_ENV
        fi
    
    - name: Set output
      id: set_output
      run: |
        echo "::set-output name=db_deleted::${{ env.db_deleted }}"
  
    - name: Print output
      run: |
        echo "DB Deleted: ${{ steps.set_output.outputs.db_deleted }}"

    - name: Stage changes
      run: |
        git add -A

    - name: Check for changes
      run: |
        git status
        git diff

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: '.'
        default_author: github_actions
        message: '[BOT] Delete database for DB number ${{ steps.set_values.outputs.db_number }}'
        push: origin ${{ github.head_ref }}

  update_db:
    needs: delete_db
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
    
    - name: Print checked out branch
      run: |
        echo "Checked out branch: $(git rev-parse --abbrev-ref HEAD)"

    - name: Set Values
      id: set_values
      run: |
        echo "db_number=2024" >> $GITHUB_ENV
        echo "week_number=18" >> $GITHUB_ENV
        echo "::set-output name=db_number::2024"
        echo "::set-output name=week_number::18"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib scikit-learn pysqlite3 beautifulsoup4 requests

    - name: Run FootballDB/main.py script
      run: python FootballDB/main.py


    - name: Stage changes
      run: |
        git add -A
      
    - name: Check for changes
      run: |
        git status
        git diff

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: '[BOT] Update database for DB number ${{ steps.set_values.outputs.db_number }}'
        push: origin ${{ github.head_ref }}
    

